import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ContactForm from "./components/ContactForm";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">My Blog</a>
        </h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed
          blandit libero volutpat sed cras. Dolor purus non enim praesent.
          Tempor id eu nisl nunc mi. Elit ut aliquam purus sit amet. At
          imperdiet dui accumsan sit amet nulla facilisi morbi.
        </p>
        <p>
          Nulla at volutpat diam ut venenatis tellus. Nulla pharetra diam sit
          amet nisl suscipit adipiscing. Viverra justo nec ultrices dui. Dolor
          sit amet consectetur adipiscing elit duis tristique sollicitudin nibh.
          Nulla aliquet enim tortor at auctor. Et malesuada fames ac turpis
          egestas maecenas pharetra.
        </p>
        <p>
          Turpis tincidunt id aliquet risus feugiat in ante. Suspendisse
          interdum consectetur libero id faucibus nisl tincidunt eget nullam.
          Mus mauris vitae ultricies leo integer malesuada nunc vel risus.
          Blandit libero volutpat sed cras ornare arcu dui vivamus arcu. Viverra
          vitae congue eu consequat ac felis donec et. Volutpat odio facilisis
          mauris sit amet massa vitae tortor condimentum.
        </p>
        Habitant morbi tristique senectus et netus et malesuada fames ac. Vel
        eros donec ac odio tempor orci dapibus. Augue lacus viverra vitae congue
        eu consequat. A cras semper auctor neque vitae. Bibendum neque egestas
        congue quisque egestas diam in arcu cursus.
        <p>
          Pellentesque diam volutpat commodo sed egestas egestas fringilla
          phasellus. Etiam non quam lacus suspendisse faucibus interdum posuere.
          Eget felis eget nunc lobortis. Enim nec dui nunc mattis enim ut
          tellus. Parturient montes nascetur ridiculus mus mauris. Nisl nunc mi
          ipsum faucibus vitae aliquet. Nibh mauris cursus mattis molestie a
          iaculis at erat. Sem et tortor consequat id porta nibh venenatis cras.
          Ultricies leo integer malesuada nunc vel risus. Purus semper eget duis
          at tellus at urna. Quis lectus nulla at volutpat diam. Massa massa
          ultricies mi quis hendrerit dolor. Felis eget velit aliquet sagittis
          id consectetur. Amet facilisis magna etiam tempor orci. Sagittis nisl
          rhoncus mattis rhoncus urna neque viverra justo.
        </p>
        <ContactForm />
      </main>
    </div>
  );
}
